services:
  grocy:
    image: linuxserver/grocy:latest
    container_name: grocy
    hostname: grocy
    ports:
      - "5000:80"
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app
